language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

before_script:
  - pecl install mongodb
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

before_script:
  - curl --version
  - composer self-update
  - composer install
